# Generated by Django 5.0.7 on 2025-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('id_number', models.CharField(max_length=120)),
                ('dob', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
