# Generated by Django 5.0.7 on 2025-10-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('theft', 'Theft'), ('murder', 'Murder'), ('child abuse', 'Child Abuse'), ('accident', 'Accident')], max_length=20)),
                ('incident_location', models.CharField(max_length=255)),
                ('incident_date', models.DateField()),
                ('incident_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('suspect_description', models.TextField(blank=True, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
