# Generated by Django 5.0.7 on 2025-10-09 22:08

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0002_casedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseDetails',
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='incident_type',
            field=models.CharField(choices=[('theft', 'Theft'), ('murder', 'Murder'), ('child abuse', 'Child Abuse'), ('accident', 'Accident')], default='theft', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='suspect_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
