# Generated by Django 5.0.7 on 2025-10-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0003_delete_casedetails_statement_incident_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_message', models.TextField()),
            ],
        ),
    ]
