# Generated by Django 5.0.7 on 2025-10-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HakiRecordApp', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='ob_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
